[phases.setup]
nixPkgs = ["nodePackages_latest.nodejs_22"]
# Railway default is often older, forcing latest v22

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
